### ISSUE TITLE
Fan mode is not available.

### ISSUE THREAD

**Issue by jhuang0** [dlarrick/pykumo#1]
The fan mode is not available. I do not have the vertical vane issue reported by the other user. The packet sniffing dump is available below - let me know if it's missing what you need.

https://drive.google.com/open?id=11TqqSlyC3YX_UE_yMxq78wMTp3HcRqYJ

**Comment by dlarrick** [comment]
Hi @jhuang0 I do see your packet capture, and it's the right stream, format, etc. But what I need for you to do is to change the fan speed from within the KumoCloud app while you're doing the capture. If you cycle through the different fan speed options, so much the better.

**Comment by jhuang0** [comment]
Here's another attempt at it....

https://drive.google.com/open?id=11XyjUDXX4yAQFiFKPKpoO1y9Zyh21fCV

**Comment by jhuang0** [comment]
Oops. Didn't mean to close it.

**Comment by dlarrick** [comment]
Aha! I think see what you mean now. You want to set it to use a ventilation function? My units don't have that (and neither does the kumojs author, evidently) but it should be easy enough to support.

**Comment by jhuang0** [comment]
Yes! It's be great if you could add support for what I see as the fan/ventilation option. I'm kind of curious to see what would happen if your unsupported model got this command. I suppose this functionality could be supported via an additional parameter in the configuration.

**Comment by dlarrick** [comment]
As it turns out the info we can get from the unit itself describes its capabilities: fan, dry (dehumidify), heat, auto fanspeed, etc. So this should be pretty flexible. I should have some time later in the week to take a look.

**Comment by dlarrick** [comment]
FYI this is resolved.
