### ISSUE TITLE
Double quote in password should be escaped

### ISSUE THREAD

**Issue by dlarrick** [dlarrick/pykumo#29]
See https://github.com/dlarrick/hass-kumo/issues/75#issuecomment-1155740011

This user had a password with a double-quote in it, which will result in early termination of the JSON string in the POST body.

https://github.com/dlarrick/pykumo/blob/master/pykumo/py_kumo_cloud_account.py#L76-L77 should be enhanced to replace a `"` in the password (and, I guess, username as well, but who does that) with `\"` prior to assembling the POST body.

**Comment by ehagan** [comment]
I changed the kumo cloud password back to one with a double quote in it and was able to fetch my units with this change.

**Comment by dlarrick** [comment]
I'll bump the version of pykumo in hass-kumo when it goes out of beta in a few days
