### ISSUE TITLE
Use without cloud service

### ISSUE THREAD

**Issue by joshourisman** [dlarrick/pykumo#33]
Sorry for misusing issues for this, but I didn’t see a better option.

Is a Kumo Cloud account actually necessary to control a unit locally? If I simply bought and installed the WiFi adapter for my unit, but didn’t set it up with the cloud service, would I be able to use Pykumo (and by extension, the Homebridge or Home Assisstant integrations) to control my Mitsubishi unit?

**Comment by dlarrick** [comment]
Cloud account is necessary for initial setup. There are credentials details ("password" and "cryptoSerial") used in talking to the device locally that are either generated by the service or algorithmically generated in some way that hasn't been reverse-engineered. Once you have these there's no reason to talk to the cloud service again. See what's done in `pykumo-demo.py`.

If you're using Home Assistant, if you enable the "prefer_cache" option on setup and your IP addresses don't change (highly recommended) it doesn't talk to the service again after that point.

The official app is also the only way (aside from begging your installer) to get into the "installer tools" to do things like set failover groups, min/max allowed setpoints, etc.

**Comment by joshourisman** [comment]
Ok, thought that might be the case. Thanks!

So I guess I have to decide if I want to pay for Kumo Cloud in order to get an installer out so I can do this, or if I want to try setting up a raspberry pi to control it directly…

**Comment by cjkrolak** [comment]
> Ok, thought that might be the case. Thanks!
> 
> So I guess I have to decide if I want to pay for Kumo Cloud in order to get an installer out so I can do this, or if I want to try setting up a raspberry pi to control it directly…

Kumocloud doesn't cost anything, you can set it up yourself.

**Comment by joshourisman** [comment]
Oh! That's good to know. Their website definitely does not make that clear… Still have to pay for the hardware, though I guess that probably ends up not being too bad compared to rolling my own with a Raspberry Pi and reverse-engineered UART protocol…

**Comment by cjkrolak** [comment]
Plug n play wifi module is $150 to $200

**Comment by joshourisman** [comment]
Oh, sweet. And it sounds like I can just plug it in myself and set up the app? The iOS app seems to think I need a professional installer with a Mitsubishi-issues PIN to configure anything.

**Comment by cjkrolak** [comment]
the installer pin is 9999, it's documented in the installer manual.

**Comment by joshourisman** [comment]
Awesome, I guess they just really want you to think you need to hire an installer. Thanks for the help!

**Comment by dlarrick** [comment]
Closing this ~issue~ discussion.
