### ISSUE TITLE
kumo_dict is not flat - need to recurse

### ISSUE THREAD

**Issue by brianr2600** [dlarrick/pykumo#5]
If the user has groups or changeover groups configured, kumo_dict may have a hierarchy of items. In my setup, all of the indoor units are in a changeover group, and so the actual items are in kumo_dict[2]['children'][0]['children']

**Comment by dlarrick** [comment]
See the 'zones' branch, pushed just yesterday. If you're using this with HomeAssistant you'll also need the 'zones' branch of https://github.com/dlarrick/hass-kumo/tree/zones .

Please report back if you try this branch. If it works for folks I'll merge it in.

**Comment by dlarrick** [comment]
Fixed by https://github.com/dlarrick/pykumo/pull/6
